version: '3'

services:
  rabbit:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 15672:15672
    volumes:
        - ./rabbit.cfg:/etc/rabbit/conf.d/10-defaults.conf

  puppeteer:
    #container_name: server
    image: 7574_tp2:latest
    entrypoint: [ "python3",  "/src/main.py", "--role", "puppeteer"]
    depends_on:
      - rabbit
    environment:
      - POST_FILTER_REPLICAS=${POST_FILTER_REPLICAS}
      - POST_AVG_REDUCERS=${POST_AVG_REDUCERS}
      - PYTHONUNBUFFERED=1
      - RABBIT_HOST=rabbit
  post_filter:
    #container_name: server
    image: 7574_tp2:latest
    deploy:
      replicas: ${POST_FILTER_REPLICAS}
    entrypoint: [ "python3",  "/src/main.py", "--role", "post_filter" ]
    depends_on:
      - puppeteer
    environment:
      - PYTHONUNBUFFERED=1
      - RABBIT_HOST=rabbit
  post_average_calculator:
    image: 7574_tp2:latest
    entrypoint: [ "python3",  "/src/main.py", "--role", "post_avg_calculator" ]
    environment:
      - PYTHONUNBUFFERED=1
      - RABBIT_HOST=rabbit
    volumes:
      - ./results/:/tmp/results/
