version: '3'

services:
  rabbit:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 15672:15672
    volumes:
        - ./rabbit.cfg:/etc/rabbit/conf.d/10-defaults.conf
  puppeteer:
    #container_name: server
    image: 7574_tp2:latest
    entrypoint: [ "python3",  "/src/main.py", "--role", "puppeteer"]
    depends_on:
      - rabbit
    environment:
      - POST_FILTER_REPLICAS=${POST_FILTER_REPLICAS}
      - POST_AVG_REDUCERS=${POST_AVG_REDUCERS}
      - STUDENT_MEME_CALCULATOR_REPLICAS=${STUDENT_MEME_CALCULATOR_REPLICAS}
      - PYTHONUNBUFFERED=1
      - RABBIT_HOST=rabbit
  post_filter:
    #container_name: server
    image: 7574_tp2:latest
    entrypoint: [ "python3",  "/src/main.py", "--role", "post_filter" ]
    depends_on:
      - puppeteer
    environment:
      - PYTHONUNBUFFERED=1
      - RABBIT_HOST=rabbit
  comment_filter:
    #container_name: server
    image: 7574_tp2:latest
    entrypoint: [ "python3",  "/src/main.py", "--role", "comment_filter" ]
    depends_on:
      - puppeteer
    environment:
      - PYTHONUNBUFFERED=1
      - RABBIT_HOST=rabbit
      - STUDENT_MEME_CALCULATOR_REPLICAS=${STUDENT_MEME_CALCULATOR_REPLICAS}
  post_average_calculator:
    image: 7574_tp2:latest
    entrypoint: [ "python3",  "/src/main.py", "--role", "post_avg_calculator" ]
    environment:
      - PYTHONUNBUFFERED=1
      - RABBIT_HOST=rabbit
  student_meme_caltulator:
    image: 7574_tp2:latest
    entrypoint: [ "python3",  "/src/main.py", "--role", "student_meme_calculator" ]
    deploy:
      replicas: 1
    environment:
      - PYTHONUNBUFFERED=1
      - RABBIT_HOST=rabbit
      - STUDENT_MEME_ALLOW_REPEATS=False
  sentiment_meme_calculator:
    image: 7574_tp2:latest
    entrypoint: [ "python3",  "/src/main.py", "--role", "sentiment_meme_calculator" ]
    environment:
      - PYTHONUNBUFFERED=1
      - RABBIT_HOST=rabbit
  post_client:
    image: 7574_tp2:latest
    entrypoint: [ "python3",  "/src/main.py", "--role", "post_client" ]
    environment:
      - PYTHONUNBUFFERED=1
      - RABBIT_HOST=rabbit
      - POSTS_FILE_PATH=/tmp/posts.csv
      - POSTS_FILE_CHUNK=10000
    volumes:
      - ./datasets/complete-posts.csv:/tmp/posts.csv
  comment_client:
    image: 7574_tp2:latest
    entrypoint: [ "python3",  "/src/main.py", "--role", "comment_client" ]
    environment:
      - PYTHONUNBUFFERED=1
      - RABBIT_HOST=rabbit
      - COMMENT_FILE_PATH=/tmp/comments.csv
      - COMMENT_FILE_CHUNK=10000
    volumes:
      - ./datasets/complete-comments.csv:/tmp/comments.csv
  result_client:
    image: 7574_tp2:latest
    entrypoint: [ "python3",  "/src/main.py", "--role", "result_client" ]
    environment:
      - PYTHONUNBUFFERED=1
      - RABBIT_HOST=rabbit
      - MEME_RESULT_PATH=/tmp/results/
      - MEME_RESULT_BUFFER=10000
    volumes:
      - ./results:/tmp/results
